amase:
  config: daidalus
  scenario: Scenario_DistributedCooperation.xml

uxases:
  - config: cfgDistributedCooperation_1000.xml
    rundir: UAV_1000

  - config: cfgDistributedCooperation_2000.xml
    rundir: UAV_2000

  - config: cfgDistributedCooperation_4208.xml
    rundir: UAV_4208
