amase:
  config: daidalus
  scenario: MessagesToSend/collision_mkii.xml

uxases:
  - config: cfgCollision_1000.xml
    rundir: UAV_1000

  - config: cfgCollision_2000.xml
    rundir: UAV_2000

  - config: cfgCollision_4208.xml
    rundir: UAV_4208