amase:
  config: daidalus
  scenario: MessagesToSend/Intersecting_Line_Search.xml

uxases:
  - config: cfgIntersecting_1000.xml
    rundir: UAV_1000

  - config: cfgIntersecting_2000.xml
    rundir: UAV_2000

  - config: cfgIntersecting_4208.xml
    rundir: UAV_4208
