amase:
  config: daidalus
  scenario: MessagesToSend/Patrol.xml

uxases:
  - config: cfgPatrol_1000.xml
    rundir: UAV_1000

  - config: cfgPatrol_2000.xml
    rundir: UAV_2000

  - config: cfgPatrol_4208.xml
    rundir: UAV_4208
